[2024-05-12T17:58:29.275+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: mlops_A2_dag.integrate_with_git scheduled__2024-05-11T17:27:34.109181+00:00 [queued]>
[2024-05-12T17:58:29.339+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: mlops_A2_dag.integrate_with_git scheduled__2024-05-11T17:27:34.109181+00:00 [queued]>
[2024-05-12T17:58:29.340+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-12T17:58:29.344+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-05-12T17:58:29.351+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-12T17:58:29.532+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): integrate_with_git> on 2024-05-11 17:27:34.109181+00:00
[2024-05-12T17:58:29.574+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_A2_dag', 'integrate_with_git', 'scheduled__2024-05-11T17:27:34.109181+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp4dw67zv4']
[2024-05-12T17:58:29.578+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask integrate_with_git
[2024-05-12T17:58:29.562+0000] {standard_task_runner.py:55} INFO - Started process 1048 to run task
[2024-05-12T17:58:30.300+0000] {task_command.py:388} INFO - Running <TaskInstance: mlops_A2_dag.integrate_with_git scheduled__2024-05-11T17:27:34.109181+00:00 [running]> on host a018cce825ad
[2024-05-12T17:58:31.134+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_A2_dag
AIRFLOW_CTX_TASK_ID=integrate_with_git
AIRFLOW_CTX_EXECUTION_DATE=2024-05-11T17:27:34.109181+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-11T17:27:34.109181+00:00
[2024-05-12T17:58:31.286+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 130, in integrate_with_git
    subprocess.run(['git', 'remote', 'add', 'origin', 'https://github.com/usman-babar/MLops_Assignment2.git'])
  File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'git'
[2024-05-12T17:58:31.545+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_A2_dag, task_id=integrate_with_git, execution_date=20240511T172734, start_date=20240512T175829, end_date=20240512T175831
[2024-05-12T17:58:31.746+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task integrate_with_git ([Errno 13] Permission denied: 'git'; 1048)
[2024-05-12T17:58:31.883+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-05-12T17:58:32.169+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
